### ISSUE TITLE
Cannot Init

### ISSUE THREAD

**Issue by monkeylord** [jolonf/bsvpush#1]
received this
~~~
(node:8040) UnhandledPromiseRejectionWarning: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at Push.init (C:\Users\Monkeylord\AppData\Roaming\npm\node_modules\bsvpush\dist\push.js:182:45)
    at Object.<anonymous> (C:\Users\Monkeylord\AppData\Roaming\npm\node_modules\bsvpush\dist\cli.js:57:29)
    at step (C:\Users\Monkeylord\AppData\Roaming\npm\node_modules\bsvpush\dist\cli.js:33:23)
    at Object.next (C:\Users\Monkeylord\AppData\Roaming\npm\node_modules\bsvpush\dist\cli.js:14:53)
    at C:\Users\Monkeylord\AppData\Roaming\npm\node_modules\bsvpush\dist\cli.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Monkeylord\AppData\Roaming\npm\node_modules\bsvpush\dist\cli.js:4:12)
    at C:\Users\Monkeylord\AppData\Roaming\npm\node_modules\bsvpush\dist\cli.js:42:23
(node:8040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
~~~

**Comment by tiagolr** [comment]
same, using Windows
